# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicQ', '0002_auto_20160513_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='choice',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
