# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicQ', '0003_auto_20160514_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
